### ISSUE TITLE
Friendships.group table missing

### ISSUE THREAD

**Issue by abdul191993** [demency/laravel-friendships#15]
![image](https://user-images.githubusercontent.com/47178064/84588140-d9df2100-ae35-11ea-9d5d-7c14501bd4c9.png)

can anyone tell me where is that group table and where is the slug for group.???

**Comment by demency** [comment]
@abdul191993 hootlex the Real creator of the package uses config file to manage Groups. Use artisan publish command.

**Comment by abdul191993** [comment]
what if i want to leave this on user so user can create a group and add his friends to that group.
can you guide me regarding this so maybe it can be more flexible way .

**Comment by demency** [comment]
@abdul191993 sorry for the late response, remember quote my name. 
Notifications doesn't works properly I think.

But answering your question: I can guide you to add your feature

In a stranger ways this package is really hard tricked. What if you overload that method? 

You can create your own Group model. Because currently, the package uses a key-valued array to manage the available groups.

We can change this to support a Group model instead static config file and that can be really easy.

**Comment by abdul191993** [comment]
thankyou for you response @demency .
so what will be the structure for group table
should i have to create many to many relation in friendships and groups table.?
if user is creating a group then his is will be there in groups table so user and groups table also relate as one to many..??

**Comment by demency** [comment]
@abdul191993 some people uses this package, we can't break something.

Anyways, I will give you some helpful links:

- [Package group model](https://github.com/demency/laravel-friendships/blob/master/src/Models/FriendFriendshipGroups.php)
- [Package group migration stub](https://github.com/demency/laravel-friendships/blob/master/migrations/0000_00_00_000000_create_friendships_groups_table.stub.php)
- [Package config file](https://github.com/demency/laravel-friendships/blob/master/config/friendships.php)

That's files can answer your initial questions. What is your use-case?

**Comment by abdul191993** [comment]
i m trying to create a groups table and i need to handle group_id in friendshipgroups table as foreign key and instead of checking group in the array i want to check groups in groups table.

**Comment by demency** [comment]
Im pretty sure about your specific use case would can't be implemented easily. Your highlighted code show some this project current caveat. I think I can take a look for a specific code what can be modified to enable your needs.

Let me make a todo with what I think we need to do to this work. Because it is really hard coded that available group checking.

@abdul191993

**Comment by abdul191993** [comment]
i have implemented the changes for a separate group table it was not difficult just changes a query from the model and created now model for groups and changes two functions groupFriend() and ungroupFriend() from the trait.

**Comment by demency** [comment]
@abdul191993 you would share your code and try to add to this repo of you like ofc.

**Comment by abdul191993** [comment]
yes i would like to share my code.

![image](https://user-images.githubusercontent.com/47178064/85948573-adadbf00-b962-11ea-9096-c3f2262c78bb.png)
![image](https://user-images.githubusercontent.com/47178064/85948612-eea5d380-b962-11ea-9a26-29b25ca0ca12.png)

**Comment by abdul191993** [comment]
i have changed two functions in friendable trait and also edit group friend scope in model and in config i have added group table

**Comment by demency** [comment]
Cool man, i'll try to make a patch with your changes.
