### ISSUE TITLE
Github Workflows

### ISSUE THREAD

**Issue by omatamix** [demency/laravel-friendships#7]
Wouldn't it be easier to test with a workflow.

**Comment by demency** [comment]
I agree with you. I already had to use it on other repositories. We should rebuild the pipepine. Focusing travis file we must redeclare those instructions using workflows. We can iterate over comments to prepare a MR.

**Comment by omatamix** [comment]
I can work on a PR for the work lows.

**Comment by demency** [comment]
Well, please submit a new PR using "Replace Travis using Workflows" and reference with this issue to do tracking.

Copy and paste the following code on PR description as initial tasks:

```
We should replace travis with github workflows:

Some initial tasks:
- [ ] Create .github/workflows folder
- [ ] Add one task.yml per supported version (6.yml, 7.yml or w/e)
- [ ] Per task add the task name definition

cc @demency 
```

Currently, Travis build the project using different PHP versions. MySql service is declared but not used because project uses :memory: driver. This repo also uses codeclimate to track some code quality stats. I use codeclimate with workflows and [here](https://github.com/Alimentalos/Backend/blob/master/.github/workflows/codeclimate.yml) is a example of laravel and codeclimate using workflow.

But nevermind, do the list and we can talk on PR to solve all doubts on the road.

This issue must be closed when the PR is done.

**Comment by omatamix** [comment]
Alright, i am on it.
